name: OSS Licenses

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Apache 2.0 License
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Install reviewdog
      uses: reviewdog/action-setup@v1

    - name: Install boilerplate-check
      run: |
        go get github.com/mattmoor/boilerplate-check/cmd/boilerplate-check

    - name: Check license boilerplate
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        reviewdog -conf=.github/workflows/config/reviewdog.yaml \
          -runners=license \
          -filter-mode=diff_context \
          -reporter=github-check \
          -fail-on-error=true
